version: "3.9"

services:
  invoice_app:
    build :
      context: .
      dockerfile: Dockerfile
    image: invoice_ocr_classifier_image
    container_name: lux_invoice_ocr_classifier
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped

